### ISSUE TITLE
Overflow exceptions from stopit

### ISSUE THREAD

**Issue by remram44** [usc-isi-i2/dsbox-cleaning#30]
When `timeout=None`, you still use stopit, but pass `math.inf` as timeout. This causes an overflow from Python's `threading`:
```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1180, in run
    self.finished.wait(self.interval)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timestamp too large to convert to C _PyTime_t
```
A better option might be to not use stopit at all when there's no timeout specified.

<details><summary>Example patch</summary>

```diff
diff --git a/dsbox/datapreprocessing/cleaner/knn.py b/dsbox/datapreprocessing/cleaner/knn.py
index b6e4f52..decf4aa 100644
--- a/dsbox/datapreprocessing/cleaner/knn.py
+++ b/dsbox/datapreprocessing/cleaner/knn.py
@@ -104,9 +104,6 @@ class KNNImputation(TransformerPrimitiveBase[Input, Output, KnnHyperparameter]):

         """

-        if (timeout is None):
-            timeout = math.inf
-
         if isinstance(inputs, pd.DataFrame):
             data = inputs.copy()
         else:
@@ -115,20 +112,19 @@ class KNNImputation(TransformerPrimitiveBase[Input, Output, KnnHyperparameter]):
         keys = data.keys()
         index = data.index

-        # setup the timeout
-        with stopit.ThreadingTimeout(timeout) as to_ctx_mrg:
-            assert to_ctx_mrg.state == to_ctx_mrg.EXECUTING
-
-            # start completing data...
+        def wrapper():
             if (self._verbose>0): print("=========> impute by fancyimpute-knn:")
-            data_clean = self.__knn(data)
+            return True, self.__knn(data)

-        result = None
-        if to_ctx_mrg.state == to_ctx_mrg.EXECUTED:
+        if timeout is not None:
+            wrapper = stopit.threading_timeoutable()(wrapper)
+
+        result = wrapper()
+        if result is not None:
             self._has_finished = True
             self._iterations_done = True
-            result = pd.DataFrame(data_clean, index, keys)
-        elif to_ctx_mrg.state == to_ctx_mrg.TIMED_OUT:
+            result = pd.DataFrame(result[1], index, keys)
+        else:
             self._has_finished = False
             self._iterations_done = False
         return CallResult(result, self._has_finished, self._iterations_done)
```
</details>

**Comment by kyao** [comment]
@luofanghao would you please take a look

**Comment by luofanghao** [comment]
thanks @remram44 , I will updates the primitives today

**Comment by remram44** [comment]
Don't worry about this too much, it is just noise in the log. Please focus on making this work on the new version of the interface
```
ValueError: Package URI does not include a commit hash: git+https://github.com/usc-isi-i2/dsbox-cleaning@v1.0#egg=dsbox-datacleaning
```
